### ISSUE TITLE
Feature Request option to ignore a binary update

### ISSUE THREAD

**Issue by ybrhue** [nao1215/gup#85]
When installing golangci-lint it is recommended to not install it via go install but instead update it manually.
So it would be nice if I could run something along the lines like:

`gup update --ignore golangci-lint`
Or even have a seperate config file.

If I run gup update bin1 bin2 … (basically all installed binaries except golangci-lint) I face the downside that when I create an alias and later add another binary, that I then have to update this alias.

Currently I just run 
`curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.52.2`
after gup update

**Comment by ybrhue** [comment]
I would also be willing to implement this change myself if you would be open to it.

**Comment by nao1215** [comment]
@ybrhue 
Thank you for the feature request.

>I would also be willing to implement this change myself if you would be open to it.

If you are creating a Pull Request that includes implementation, added unit tests, and updated README, you may add the --ignore option to gup commad if you wish.
The gup command is a bit difficult to write unit tests for because I made it when I wasn't familiar with Golang.

I think it would be more convenient if the -ignore (-i) option could accept multiple command names as option arguments, like this.
```
$ gup update --ignore foo,bar
```

I think it would be a good idea to write a function to remove the commands specified by --ignore from the list of target commands right after the code line `pkgs = extractUserSpecifyPkg(pkgs, args).`
https://github.com/nao1215/gup/blob/cb54aa4ecb44ff7c642ee5ce91330ccb8656dbab/cmd/update.go#L66-L76

**Comment by nao1215** [comment]
#86

**Comment by nao1215** [comment]
@hueuebi
Thank you for your PR. I have released the v0.21.0. This version include your PR.
https://github.com/nao1215/gup/releases/tag/v0.21.0
